# Generated by Django 3.0.7 on 2020-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.CharField(default=10, max_length=15),
            preserve_default=False,
        ),
    ]
