# Generated by Django 3.0.7 on 2020-07-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_userinfo_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='addapps',
            fields=[
                ('app_id', models.UUIDField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=15)),
                ('webaddress', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userInfo')),
            ],
        ),
    ]
