# Generated by Django 3.0.7 on 2020-07-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200701_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addapps',
            name='app_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
