# Generated by Django 2.1.15 on 2020-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200713_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
