# Generated by Django 2.1.15 on 2020-07-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addapps',
            fields=[
                ('app_id', models.UUIDField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=15)),
                ('webaddress', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='APP',
            fields=[
                ('app_id', models.UUIDField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=15)),
                ('webaddress', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key_id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.company'),
        ),
        migrations.AddField(
            model_name='addapps',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.userInfo'),
        ),
    ]
